### PR TITLE
Fix missing ImageIcon for PlayButton and repeated EndScreen Spawning

### LINKED ISSUE #2: Latest Release not working on Microsoft Windows
When starting the JAR file with the latest release of the game, an empty window titled "End Screen" appears.

I have obtained a stack trace which might help you in finding the cause of this bug:
`java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
        at dev.lh.snake.Endscreen.<init>(Endscreen.java:101)
        at dev.lh.snake.Snake.tick(Snake.java:135)
        at dev.lh.snake.GameWindow.lambda$0(GameWindow.java:120)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

It looks like it could have to do with texture loading, e.g. a texture not being accessible inside the JAR.

### PR DESCRIPTION
**Pull request by CyB3RC0nN0R**
Closes #2

### CODE REVIEW

File: src/main/dev/lh/ui/StartScreen.java [hunk 1]
```diff
@@ -59,17 +61,17 @@ public StartScreen() {
 
 			JButton buPlay = new JButton("Start Game");
 			buPlay.setBounds(158, 197, 190, 131);
-			buPlay.setIcon(new ImageIcon(StartScreen.class.getResource("/com/sun/javafx/webkit/prism/resources/mediaPlayDisabled.png")));
+			buPlay.setText("Play");
```
Comment (delvh) [inline src/main/dev/lh/ui/StartScreen.java]:
```suggestion
			buPlay.setText("Play Again");
```

**Review by delvh — APPROVED** [review]
I already wondered why infinitely many Endscreens were spawning...
Thanks for fixing that world-moving issue!
